name: ejemplo
on:
  push:
    branches: [ main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: action/setup-python@v5
      with:
        python-version: '3.11'
    - run: python ./ejemplos/EjemploAction.py
    
