name: programado
on:
  schedule:
    - cron: '1 1 1 1  *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - run: python ./EjemploAction.py
